package com.etips;

import com.etips.models.InputState;
import com.etips.models.Player;
import com.etips.models.Game;
import com.etips.models.enums.PlayerForm;
import java.time.LocalDateTime;


rule "Classify Player Form - In Form"
    when
    	$i: InputState( resultState == ResultState.NA, $p: player, $games: player.gamesPlayed, $name: player.name, $surname: player.surname )
    	$pl: Player( id == $p.getId() )
        accumulate(
        	Game($gMont: this, date.isAfter(LocalDateTime.now().minusMonths(1)), $pointsMonth: points) from $games and
        	Game($g: this, $points: points) from $games,
        	$averageMonth: average($pointsMonth),
        	$average: average($points)
        )
        eval($averageMonth >= $average)
    then
    	System.out.println($name + " " + $surname + " is in form");
    	modify($pl) { setPlayerForm( PlayerForm.IN_FORM ); }
end

rule "Classify Player Form - Out of Form"
    when
        $i: InputState( $p: player, $games: player.gamesPlayed, $name: player.name, $surname: player.surname )
        $pl: Player( id == $p.getId() )
        accumulate(
        	Game($gMont: this, date.isAfter(LocalDateTime.now().minusMonths(1)), $pointsMonth: points) from $games and
        	Game($g: this, $points: points) from $games,
        	$averageMonth: average($pointsMonth),
        	$average: average($points)
        )
        eval($averageMonth < $average)
    then
    	System.out.println($name + " " + $surname + " is out of form");
    	modify($pl) { setPlayerForm( PlayerForm.OUT_OF_FORM ); }
end

rule "Classify Player Form Out of Form and Injury"
	no-loop true
	when
		$i: InputState( $p: player )
		$pl: Player( id == $p.getId(), $name: name, $surname: surname, $pf: playerForm, $pf == PlayerForm.OUT_OF_FORM, injury == true )
	then
		System.out.println($name + " " + $surname + " is extremely out form");
		modify($pl) { setPlayerForm( PlayerForm.EXTREMELY_OUT_OF_FORM ); }
end

rule "Classify Player Form - In Form and Injury"
	no-loop true
	when
		$i: InputState( $p: player )
		$pl: Player( id == $p.getId(), $name: name, $surname: surname, $pf: playerForm, $pf == PlayerForm.IN_FORM, injury == true )
	then
		System.out.println($name + " " + $surname + " is out of form!");
		modify($pl) { setPlayerForm( PlayerForm.OUT_OF_FORM ); }
end