package com.etips;

import com.etips.models.Player;
import com.etips.models.InputState;
import com.etips.models.Game;
import java.time.LocalDateTime;

rule "Player was injured"
	when
		$i: InputState( $p: player, $games: player.gamesPlayed )
		$player: Player( name == $p.name, surname == $p.surname )
		Number(intValue >= 2) from accumulate(
			Game(
				$dateMonth: date,
				$dateMonth.isAfter(LocalDateTime.now().minusDays(10)),
				played == false
			) from $games,
			init(int count = 0;),
			action(count += 1;),
			result(count)
		)
	then
		modify($player) { setInjury( true ); }
end