package com.etips;

import com.etips.models.Player;
import com.etips.models.InputState;
import com.etips.models.Game;
import java.time.LocalDateTime;
import java.util.List;

rule "Player was injured"
	when
		$i: InputState( formCalculated == false, $p: player, $games: player.gamesPlayed, $name: player.name, $surname: player.surname )
		Number(intValue >= 2) from accumulate(
			Game(
				date.isAfter(LocalDateTime.now().minusDays(10)),
				played == false
			) from $games,
			count()
		)
	then
		System.out.println($name + " " + $surname + " is injured.");
		modify($i) { setPlayerInjury(true); }
end