package com.etips;

import com.etips.models.Player;
import com.etips.models.InputState;
import com.etips.models.Game;
import com.etips.models.enums.ResultState;
import java.time.LocalDateTime;
import java.util.List;

rule "Player was injured"
	when
		$i: InputState( $p: player, formCalculated == false, $games: player.gamesPlayed, resultState == ResultState.NA )
		$pl: Player( id == $p.getId(), $name: name, $surname: surname )
		Number(intValue >= 2) from accumulate(
			Game(
				date.isAfter(LocalDateTime.now().minusDays(10)),
				played == false
			) from $games,
			count()
		)
	then
		System.out.println($name + " " + $surname + " is injured.");
		modify($pl) { setInjury(true); }
end