//created on: Jun 6, 2022
package com.etips

//list any import classes here.
import com.etips.models.Game;
import com.etips.models.Player;
import com.etips.models.Club;
import com.etips.models.QueryResults;


//declare any global variables here




rule "average points forall"
	no-loop
    when
        $q: QueryResults()
        AveragePoints(name, surname, club, $avg;)
    then
        System.out.println(name + " " + surname + " vs club " + club + " has average of " + $avg);
        modify($q){addResult(name + " " + surname + " vs club " + club + " has average of " + $avg)}

end

query AveragePoints(String name, String surname, String clubName, Double $avg)
	$p: Player(name, surname;)
	$c: Club(clubName;)
	accumulate(
		Game($points: points, player == $p, opposingClub == $c),
		$avg:= average($points)
	)
end
